services:
  app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://jira_user:admin@jira_clone_db:5432/jira_clone_db
    depends_on:
      jira_clone_db:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  jira_clone_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jira_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jira_clone_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jira_user -d jira_clone_db"]
      interval: 5s
      retries: 5
      start_period: 10s

  tests:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://jira_user:admin@jira_clone_db:5432/jira_clone_db
      BASE_URL: http://app:3000
    depends_on:
      app:
        condition: service_healthy
    command: ["sh", "-c", "sleep 30 && npx playwright test"]
    volumes:
      - ./playwright-report:/app/jira-clone-testing-playwright-jmeter/playwright-report  # Persist Playwright report
