# fly.toml file generated for jira-clone on 2023-01-13T19:03:42+01:00

app = "jira-clone"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
DATABASE_URL = "file:/data/jira_clone.db"

[mounts]
destination = "/data"
source = "data"

[[services]]
http_checks = []
internal_port = 3000
processes = ["app"]
protocol = "tcp"
script_checks = []
tcp_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[statics]]
guest_path = "/app/public"
url_prefix = "/public"
