name: Build, Push, and Run Playwright Tests

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DS_USER_ID=${{ secrets.DS_USER_ID }}" >> .env
          echo "AD_USER_ID=${{ secrets.AD_USER_ID }}" >> .env
          echo "W_USER_ID=${{ secrets.W_USER_ID }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        working-directory: /home/runner/work/jira-clone-testing-playwright-jmeter/jira-clone-testing-playwright-jmeter

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dramos84/jira-clone-tests:latest

      - name: Tag with Commit SHA
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dramos84/jira-clone-tests:${{ github.sha }}

      - name: Build Docker Image
        run: docker-compose build
        working-directory: /home/runner/work/jira-clone-testing-playwright-jmeter/jira-clone-testing-playwright-jmeter

      - name: Start Services with Docker Compose
        run: docker-compose up -d
        working-directory: /home/runner/work/jira-clone-testing-playwright-jmeter/jira-clone-testing-playwright-jmeter

      - name: Wait for Services to be Healthy
        run: docker-compose exec app sh -c "while ! curl -sSf http://localhost:3000 > /dev/null; do sleep 5; done"

      - name: Ensure Playwright report directory is clean
        run: |
          if [ -d "playwright-report" ]; then
            rm -rf playwright-report/*
          else
            mkdir -p playwright-report
          fi

      - name: Run Playwright Tests in Docker (Using .env)
        run: |
          docker run --rm \
            --network="host" \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DS_USER_ID=${{ secrets.DS_USER_ID }} \
            -e AD_USER_ID=${{ secrets.AD_USER_ID }} \
            -e W_USER_ID=${{ secrets.W_USER_ID }} \
            -e CI=true \
            dramos84/jira-clone-tests:latest \
            sh -c "npx playwright test && exit 0"

      - name: Verify Playwright report directory
        run: |
          if [ ! -d "playwright-report" ] || [ -z "$(ls -A playwright-report)" ]; then
            echo "No Playwright report found."
            exit 1

      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: playwright-report
          retention-days: 7
