name: Build, Push Docker Image & Run Playwright Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dramos84/jira-clone-tests:latest

      - name: Tag with Commit SHA
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dramos84/jira-clone-tests:${{ github.sha }}

  run-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Playwright Tests inside Docker
        run: |
          docker run --rm \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DS_USER_ID=${{ secrets.DS_USER_ID }} \
            -e AD_USER_ID=${{ secrets.AD_USER_ID }} \
            -e W_USER_ID=${{ secrets.W_USER_ID }} \
            dramos84/jira-clone-tests:latest \
            npx playwright test